#!/usr/bin/env kr
// Objective-K Synapse launcher and privacy-context control surface.

import "k:okui"
import "k:proc_ex"
import "head:windows"
import "../core/privacy.k"
import "../core/i2p.k"

func quote(value) {
    emit fromCharCode(34) + value + fromCharCode(34)
}

func chomp(value) {
    let end = len(value)
    while end > 0 {
        let code = charCode(value[end - 1])
        if code == 10 || code == 13 || code == 32 || code == 9 { end -= 1 }
        else { break }
    }
    emit substring(value, 0, end)
}

func winSlash() { emit fromCharCode(92) }

func joinPath(base, child) {
    emit base + winSlash() + child
}

func exists(path) {
    let output = exec("if exist " + quote(path) + " (echo yes) else (echo no)")
    emit contains(output, "yes")
}

func envValue(name) {
    let raw = chomp(exec("set " + name))
    let prefix = name + "="
    if indexOf(raw, prefix) == 0 {
        emit substring(raw, len(prefix), len(raw))
    }
    emit ""
}

func isSafeAbsolutePath(path) {
    if len(path) < 4 { emit "0" }
    let code = charCode(path[0])
    let isUpper = code >= 65 && code <= 90
    let isLower = code >= 97 && code <= 122
    if !isUpper && !isLower { emit "0" }
    if path[1] != ":" { emit "0" }
    if path[2] != "\\" && path[2] != "/" { emit "0" }
    if contains(path, fromCharCode(34)) { emit "0" }
    if contains(path, "'") { emit "0" }
    if contains(path, "&") { emit "0" }
    if contains(path, "|") { emit "0" }
    if contains(path, "<") { emit "0" }
    if contains(path, ">") { emit "0" }
    if contains(path, "%") || contains(path, "!") { emit "0" }
    if contains(path, fromCharCode(10)) || contains(path, fromCharCode(13)) { emit "0" }
    emit "1"
}

func fullPath(path) {
    if isSafeAbsolutePath(path) != "1" { emit "" }
    emit chomp(exec("for %I in (" + quote(path) + ") do @echo %~fI"))
}

func directoryName(path) {
    let index = len(path) - 1
    while index >= 0 {
        if path[index] == "\\" || path[index] == "/" {
            emit substring(path, 0, index)
        }
        index -= 1
    }
    emit ""
}

func isWorkspace(path) {
    let control = joinPath(joinPath(joinPath(path, "src"), "control"), "run.ks")
    let state = joinPath(path, ".synapse-build")
    if exists(control) && exists(state) { emit "1" }
    emit "0"
}

func findWorkspace(start) {
    let candidate = fullPath(start)
    let depth = 0
    while len(candidate) > 3 && depth < 8 {
        if isWorkspace(candidate) == "1" { emit candidate }
        let parent = fullPath(joinPath(candidate, ".."))
        if len(parent) == 0 || parent == candidate { break }
        candidate = parent
        depth += 1
    }
    emit ""
}

func workspaceRoot() {
    let configured = envValue("SYNAPSE_WORKSPACE_ROOT")
    if len(configured) > 0 {
        let configuredRoot = findWorkspace(configured)
        if len(configuredRoot) > 0 { emit configuredRoot }
    }

    let imagePath = processImagePath(GetCurrentProcessId())
    if len(imagePath) > 0 {
        let imageRoot = findWorkspace(directoryName(imagePath))
        if len(imageRoot) > 0 { emit imageRoot }
    }

    emit findWorkspace(chomp(exec("cd")))
}

func buildRoot(workspace) {
    emit joinPath(workspace, ".synapse-build")
}

func browserPath(workspace) {
    let root = buildRoot(workspace)
    emit joinPath(joinPath(joinPath(joinPath(root, "obj-synapse"), "dist"), "bin"), "firefox.exe")
}

func identityFolder(label) {
    if label == "Personal" { emit "personal" }
    if label == "Work" { emit "work" }
    if label == "School" { emit "school" }
    if label == "Creator" { emit "creator" }
    if label == "Second account" { emit "second-account" }
    emit "personal"
}

func profileRoot() {
    let local = fullPath(envValue("LOCALAPPDATA"))
    if len(local) == 0 { emit "" }
    emit joinPath(joinPath(local, "Synapse"), "Profiles")
}

func profilePath(mode, identity) {
    let root = profileRoot()
    if len(root) == 0 { emit "" }
    let folder = "synapse-" + identityFolder(identity)
    if mode == "i2p" { folder = i2pProfileFolder(identityFolder(identity)) }
    emit joinPath(root, folder)
}

func enforceI2pProfilePrefs(profile) {
    let target = joinPath(profile, "user.js")
    let staged = target + ".synapse-new"
    let expected = i2pUserPrefs()
    if exists(target) && !startsWith(readFile(target), "// Generated by Synapse.") {
        emit "0"
    }


    // Stage and verify before replacing the Synapse-owned startup policy. This
    // lets security-pref updates apply without leaving a partial user.js.
    writeFile(staged, expected)
    if !exists(staged) || readFile(staged) != expected { emit "0" }

    let replaceCommand = "move /Y " + quote(staged) + " " + quote(target) + " >nul"
    replaceCommand = replaceCommand + " & if errorlevel 1 (echo no) else (echo yes)"
    if !contains(exec(replaceCommand), "yes") { emit "0" }
    if exists(target) && readFile(target) == expected { emit "1" }
    emit "0"
}

func legacyProfilePath(workspace, identity) {
    emit joinPath(
        joinPath(buildRoot(workspace), "profiles"),
        "synapse-" + identityFolder(identity)
    )
}

func bind(control, mode, identity, details, status) {
    doSet(control, "mode", mode)
    doSet(control, "identity", identity)
    doSet(control, "details", details)
    doSet(control, "status", status)
    emit done()
}

func showMode(sender) {
    let modeControl = get(sender, "mode")
    let details = get(sender, "details")
    let status = get(sender, "status")
    let mode = privacyModeFromLabel(choice(modeControl))

    doTextBox(details, privacyModeLabel(mode) + "\r\n\r\n" + privacySummary(mode))
    if mode == "shield" {
        doText(status, "Shield policy integration in progress")
        emit done()
    }
    if mode == "i2p" {
        doText(status, "I2P+ proxy configured at 127.0.0.1:4444; direct fallback remains disabled")
        emit done()
    }
    doText(status, "Fail closed: this context is not engine-enforced yet")
    emit done()
}

func onIdentityHelp(self, cmd, sender) {
    let details = get(sender, "details")
    let status = get(sender, "status")
    doTextBox(
        details,
        "Browser identities\r\n\r\nEach mode and identity pair has its own cookies, logins, history, extensions, cache, and open windows. Personal in Shield never shares a Gecko profile with Personal in I2P. Use Personal and Work at the same time to stay signed into different accounts on the same website.\r\n\r\nSynapse stores durable Shield and I2P profiles under your Windows local-app-data Synapse\\Profiles folder and starts -no-remote processes. It does not copy passwords or cookies between profiles."
    )
    doText(status, "Choose an identity, then launch it")
    emit done()
}

func onDescribe(self, cmd, sender) {
    emit showMode(sender)
}

func onLaunch(self, cmd, sender) {
    let modeControl = get(sender, "mode")
    let identityControl = get(sender, "identity")
    let status = get(sender, "status")
    let mode = privacyModeFromLabel(choice(modeControl))
    let identity = choice(identityControl)

    // Only modes with implemented startup enforcement may launch.
    if mode != "shield" && mode != "i2p" {
        doText(status, "Launch blocked: " + privacyModeLabel(mode) + " is not enforced yet")
        emit done()
    }

    let workspace = workspaceRoot()
    if len(workspace) == 0 {
        doText(status, "Launch blocked: Synapse workspace was not found")
        emit done()
    }

    let browser = browserPath(workspace)
    let profile = profilePath(mode, identity)
    let legacyProfile = legacyProfilePath(workspace, identity)
    if !exists(browser) {
        doText(status, "Launch blocked: build Synapse first")
        emit done()
    }
    if len(profile) == 0 {
        doText(status, "Launch blocked: Windows local app-data path is unavailable")
        emit done()
    }

    // Copy an earlier prototype profile once. Keep its source as recovery data.
    if mode == "shield" && !exists(profile) && exists(legacyProfile) {
        let migrationProfile = profile + ".migrating"
        let migrationCommand = "robocopy " + quote(legacyProfile) + " " + quote(migrationProfile)
        migrationCommand = migrationCommand + " /E /COPY:DAT /DCOPY:T /R:2 /W:1 /NFL /NDL /NP >nul"
        migrationCommand = migrationCommand + " & if errorlevel 8 (echo no) else ("
        migrationCommand = migrationCommand + "if exist " + quote(profile) + " (echo no) else ("
        migrationCommand = migrationCommand + "move /Y " + quote(migrationProfile) + " " + quote(profile) + " >nul"
        migrationCommand = migrationCommand + " & if exist " + quote(profile) + " (echo yes) else (echo no)))"
        if !contains(exec(migrationCommand), "yes") {
            doText(status, "Launch blocked: older identity profile could not be migrated")
            emit done()
        }
    }

    let profileCommand = "if not exist " + quote(profile) + " mkdir " + quote(profile)
    profileCommand = profileCommand + " & if exist " + quote(profile) + " (echo yes) else (echo no)"
    if !contains(exec(profileCommand), "yes") {
        doText(status, "Launch blocked: development profile could not be created")
        emit done()
    }
    if mode == "i2p" && enforceI2pProfilePrefs(profile) != "1" {
        doText(status, "Launch blocked: I2P startup policy could not be written and verified")
        emit done()
    }

    let launchCommand = "set MOZ_CRASHREPORTER_NO_REPORT=1&& start " + quote("") + " " + quote(browser)
    launchCommand = launchCommand + " -no-remote -profile " + quote(profile)
    if mode == "i2p" { launchCommand = launchCommand + " about:blank" }
    launchCommand = launchCommand + " & if errorlevel 1 (echo no) else (echo yes)"
    if !contains(exec(launchCommand), "yes") {
        doText(status, "Launch failed: Windows could not start Synapse")
        emit done()
    }

    if mode == "i2p" {
        doText(status, "I2P " + identity + " started; proxy prefs point to 127.0.0.1:4444")
        emit done()
    }
    doText(status, identity + " started in its own signed-in browser instance")
    emit done()
}

func onBuild(self, cmd, sender) {
    let status = get(sender, "status")
    let workspace = workspaceRoot()
    if len(workspace) == 0 {
        doText(status, "Build blocked: Synapse workspace was not found")
        emit done()
    }

    let tool = joinPath(joinPath(workspace, "dist"), "synapse-tool.exe")
    if !exists(tool) {
        doText(status, "Build blocked: Synapse controller was not found")
        emit done()
    }

    let command = "start " + quote("Synapse build") + " " + quote(tool) + " build"
    exec(command)
    doText(status, "Build started; log: " + joinPath(buildRoot(workspace), "mach-build.log"))
    emit done()
}

just run {
    app("Synapse Control")
    let win = window("Synapse Control", 720, 470)
    minSize(win, 660, 430)
    doTransparentTitlebar(win)
    doWindowBackground(win, rgb(244, 247, 251))

    let brand = title(win, "Synapse", area(28, 414, 220, 30))
    doFont(brand, fontFamily(mono(16), "Segoe UI Semibold"))
    label(win, "Private by design. Honest by default.", area(220, 417, 350, 24))

    label(win, "Privacy mode", area(28, 356, 126, 24))
    let mode = choices(win, area(154, 352, 186, 160))
    doAddChoice(mode, "Shield")
    doAddChoice(mode, "Private")
    doAddChoice(mode, "Tor")
    doAddChoice(mode, "I2P")
    doAddChoice(mode, "Blackout")
    doChoose(mode, 0)

    label(win, "Browser identity", area(360, 356, 112, 24))
    let identity = choices(win, area(470, 352, 142, 160))
    doAddChoice(identity, "Personal")
    doAddChoice(identity, "Work")
    doAddChoice(identity, "School")
    doAddChoice(identity, "Creator")
    doAddChoice(identity, "Second account")
    doChoose(identity, 0)
    let identityHelp = button(win, "?", area(620, 352, 28, 32))
    let launch = button(win, "Open", area(654, 352, 54, 32))

    let details = textBox(win, area(28, 102, 650, 224))
    doEditable(details, 0)
    doTextBox(details, "Shield\r\n\r\n" + privacySummary("shield"))

    let describe = button(win, "What this mode means", area(28, 50, 164, 32))
    let build = button(win, "Build Synapse", area(204, 50, 142, 32))
    let status = label(win, "Gecko engine ready", area(364, 55, 314, 24))

    bind(describe, mode, identity, details, status)
    bind(identityHelp, mode, identity, details, status)
    bind(launch, mode, identity, details, status)
    doSet(build, "status", status)

    doClick(describe, "synapse.describe", funcptr(onDescribe))
    doClick(identityHelp, "synapse.identity.help", funcptr(onIdentityHelp))
    doClick(launch, "synapse.launch", funcptr(onLaunch))
    doClick(build, "synapse.build", funcptr(onBuild))

    doShow(win)
    doRun()
}
