#!/usr/bin/env bash
set -euo pipefail

workspace="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
firefox_root="${SYNAPSE_FIREFOX_ROOT:-$HOME/mozilla-source/firefox}"
build_root="$workspace/.synapse-build"
obj_root="$build_root/obj-synapse"
mozbuild_root="$build_root/mozbuild"

fail() {
  printf 'Synapse: %s\n' "$*" >&2
  exit 1
}

need_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command is missing: $1"
}

check_roots() {
  [[ -f "$workspace/tools/synapse.ks" ]] || fail "workspace is not a Synapse repository: $workspace"
  [[ -f "$firefox_root/mach" ]] || fail "Firefox source is missing: $firefox_root"
  [[ "$workspace" != "$firefox_root" ]] || fail "Synapse and Firefox roots must be separate"
}

doctor() {
  local failures=0
  printf 'Workspace root: %s\n' "$workspace"
  printf 'Firefox root: %s\n' "$firefox_root"
  printf 'Host: macOS %s (%s)\n' "$(sw_vers -productVersion)" "$(uname -m)"

  for command in git rsync python3; do
    if command -v "$command" >/dev/null 2>&1; then
      printf '%s: ok\n' "$command"
    else
      printf '%s: missing\n' "$command"
      failures=$((failures + 1))
    fi
  done

  if command -v kcc >/dev/null 2>&1; then
    printf 'Krypton compiler: ok (%s)\n' "$(command -v kcc)"
  else
    printf 'Krypton compiler: missing\n'
    failures=$((failures + 1))
  fi

  if [[ -f "$firefox_root/mach" ]]; then
    printf 'Firefox source: ok\n'
  else
    printf 'Firefox source: missing (%s)\n' "$firefox_root"
    failures=$((failures + 1))
  fi

  ((failures == 0)) || fail "$failures required check(s) failed"
  printf 'Doctor: ready\n'
}

install_mozconfig() {
  local template="$workspace/config/mozconfig.in"
  local target="$firefox_root/mozconfig"

  if [[ -f "$target" ]] && ! grep -q '^# Generated by Synapse' "$target"; then
    [[ -f "$target.pre-synapse" ]] || cp -p "$target" "$target.pre-synapse"
  fi

  sed \
    -e "s|@SYNAPSE_WORKSPACE_NATIVE@|$workspace|g" \
    -e "s|@SYNAPSE_WORKSPACE_MSYS@|$workspace|g" \
    "$template" >"$target"
  grep -q '@SYNAPSE_WORKSPACE_' "$target" && fail "mozconfig has unresolved placeholders"
  printf 'Installed Synapse mozconfig: %s\n' "$target"
}

apply_privacy_patch() {
  local patch="$workspace/overlay/privacy/privacy-loader.patch"
  if git -C "$firefox_root" apply --check "$patch" >/dev/null 2>&1; then
    git -C "$firefox_root" apply "$patch"
    printf 'Applied Synapse privacy loader patch.\n'
  elif git -C "$firefox_root" apply --reverse --check "$patch" >/dev/null 2>&1; then
    printf 'Synapse privacy loader patch is already applied.\n'
  else
    fail "privacy loader patch no longer applies cleanly"
  fi
}

apply_overlay() {
  check_roots
  need_command rsync
  printf 'Applying Synapse browser overlay without deleting upstream files...\n'
  rsync -a "$workspace/overlay/browser/" "$firefox_root/browser/"
  [[ -f "$firefox_root/browser/branding/synapse/configure.sh" ]] || fail "branding overlay verification failed"
  [[ -f "$firefox_root/browser/app/profile/synapse.js" ]] || fail "privacy preferences verification failed"
  apply_privacy_patch
  install_mozconfig
  printf 'Apply: complete\n'
}

run_mach() {
  local label="$1"
  shift
  doctor
  apply_overlay
  mkdir -p "$build_root" "$mozbuild_root"
  local log="$build_root/mach-$label.log"
  printf 'Running: mach %s\nLog: %s\n' "$*" "$log"
  if MOZBUILD_STATE_PATH="$mozbuild_root" "$firefox_root/mach" "$@" >"$log" 2>&1; then
    printf 'Mach %s: complete\n' "$label"
  else
    tail -n 80 "$log" >&2 || true
    fail "mach $label failed"
  fi
}

run_core_tests() {
  need_command kcc
  mkdir -p "$build_root"
  kcc "$workspace/tests/run.ks" -o "$build_root/synapse-tests"
  if ! "$build_root/synapse-tests"; then
    fail "Krypton core contracts failed"
  fi
}

usage() {
  cat <<'EOF'
Synapse macOS controller
  tools/synapse-macos.sh doctor
  tools/synapse-macos.sh apply
  tools/synapse-macos.sh build
  tools/synapse-macos.sh faster
  tools/synapse-macos.sh run
  tools/synapse-macos.sh package
  tools/synapse-macos.sh test-extension
  tools/synapse-macos.sh test-core

Optional environment:
  SYNAPSE_FIREFOX_ROOT  Firefox source checkout (default: ~/mozilla-source/firefox)
EOF
}

command_name="${1:-}"
case "$command_name" in
  doctor) doctor ;;
  apply) apply_overlay ;;
  build) run_mach build build ;;
  faster) run_mach faster build faster ;;
  run) run_mach run run --no-remote ;;
  package) run_mach package package ;;
  test-extension)
    run_mach test-extension test \
      browser/components/extensions/test/browser/browser_ext_browserAction_simple.js \
      --setpref dom.security.https_only_mode=false \
      --setpref dom.security.https_only_mode_pbm=false \
      --setpref network.lna.enabled=false \
      --setpref network.lna.blocking=false
    ;;
  test-core) run_core_tests ;;
  -h|--help|"") usage ;;
  *) usage >&2; fail "unknown command: $command_name" ;;
esac
